# Aula 3 : Multiplicaçao e divisao

In [1]:
import numpy as np
import sympy as sp

from IPython.display import display, Math

In [2]:
class ObjQuantico:
    def __init__(self, data,latex_representation=None):
        self.dados = data
        self.latex_representation = latex_representation

    def definir_dados(self, data):
        self.dados = data

    def full(self):
        return self.dados
    
    def dim(self):
        return len(self.dados)
    
    def dag(self):
        return ObjQuantico(np.conjugate(self.dados.T))
    
    def traço(self):
        return np.trace(self.dados).real
    
    def Autovalores(self):
        return np.linalg.eigvals(self.dados)
    
    def Autovetores(self):
        return np.linalg.eig(self.dados)[1]
    
    def AutoValor_vetor(self):
        return np.linalg.eig(self.dados)[1]
    
    def __repr__(self):
        if self.latex_representation:
            display(Math(self.latex_representation))
        else:
            display(Math(sp.latex(sp.Matrix(self.dados))))
        return f"ObjQuantico: dim ={self.dim()} , shape = {self.dados.shape}" 
    
    def __mul__(self, other):
        # Multiplicação para diferentes tipos
        if isinstance(other, ObjQuantico):  
            # Multiplicação matricial com outra instância de ObjQuantico
            return ObjQuantico(np.dot(self.dados, other.dados))
        elif np.isscalar(other):  # Multiplicação por escalar
            return ObjQuantico(self.dados * other)
        else:
            raise TypeError(f"Multiplicação não suportada entre {type(other)} e ObjQuantico")

    def __rmul__(self, other):
        if np.isscalar(other):  # Multiplicação reversa por escalar
            return ObjQuantico(self.dados * other)
        else:
            raise TypeError(f"Multiplicação não suportada entre {type(other)} e ObjQuantico")
        
    def __sub__(self, other):
        if isinstance(other, ObjQuantico):  
            # Subtração entre duas instâncias de ObjQuantico
            return ObjQuantico(self.dados - other.dados)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")
       
    def __add__(self, other):
        if isinstance(other, ObjQuantico):  
            # Soma os dados de dois objetos ObjQuantico
            return ObjQuantico(self.dados + other.dados)
        else:
            raise TypeError(f"Soma não suportada entre {type(other)} e ObjQuantico")
        
    def __sub__(self, other):
        if isinstance(other, ObjQuantico):  
            # Subtração entre duas instâncias de ObjQuantico
            return ObjQuantico(self.dados - other.dados)
        elif isinstance(other, np.ndarray):  # Subtração com arrays NumPy
            return ObjQuantico(self.dados - other)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")
    
    def __rsub__(self, other):
        if isinstance(other, np.ndarray):  # Subtração com arrays NumPy (comutada)
            return ObjQuantico(other - self.dados)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")   

    def __truediv__(self, other):
        if isinstance(other, (int, float)):  # Divisão por um número escalar
            return ObjQuantico(self.dados / other)
        else:
            raise TypeError(f"Divisão não suportada entre {type(other)} e ObjQuantico")
    
    def __rtruediv__(self, other):
        if isinstance(other, (int, float)):  # Divisão invertida por um número escalar
            return ObjQuantico(other / self.dados)
        else:
            raise TypeError(f"Divisão não suportada entre {type(other)} e ObjQuantico")     
    
    def __matmul__(self, other):
        """Implementa o operador @ para o produto tensorial."""
        if isinstance(other, ObjQuantico):
            return ObjQuantico(np.kron(self.full(), other.full()))
        else:
            raise TypeError(f"Operador @ não suportado entre {type(self)} e {type(other)}")

def bases(N,n):
    estadoinicial = np.zeros(shape=(N, 1))
    estadoinicial[n, 0] = 1
    return ObjQuantico(estadoinicial) 
  
def ket(entrada):
    if isinstance(entrada, str):
        if entrada == '0':
            dados = np.array([[1], [0]])
            latex_representation = r"$$ \ket{0} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
        elif entrada == '1':
            dados = np.array([[0], [1]])
            latex_representation = r"$$ \ket{1} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
    else:
        try:
            return ObjQuantico(entrada)
        except ValueError:
            return print("Entrada invalida.") 
         
def bra(entrada):
    if isinstance(entrada, str):
        if entrada == '0':
            dados = ket('0').dag().full()
            latex_representation = r"$$ \bra{0} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
        elif entrada == '1':
            dados = ket('1').dag().full()
            latex_representation = r"$$ \bra{1} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
    else:
        try:
            return ObjQuantico(entrada)
        except ValueError:
            return print("Entrada invalida.")      

def Identidade(N):
    matriz = np.identity(N)
    return ObjQuantico(matriz) 

## Multiplicação por escalar

$$2*\ket{0} =  \left(\begin{matrix}2.0\\0.0\\\end{matrix}\right)$$

In [3]:
2*bases(2,0)

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 1)

In [4]:
2*bases(2,1)*2

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 1)

$$(9-1j)*\ket{0} =  \left(\begin{matrix}(9-1j)\\0.0\\\end{matrix}\right)$$

In [5]:
(9-1j)*ket('0')

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 1)

In [6]:
(1-7j)*Identidade(3)

<IPython.core.display.Math object>

ObjQuantico: dim =3 , shape = (3, 3)

## Produto interno

$$< 0|0> =< 1|1> = 1  $$

In [7]:
ket('0').dag()*ket('0') 

<IPython.core.display.Math object>

ObjQuantico: dim =1 , shape = (1, 1)

In [8]:
bra('0').full()

array([[1, 0]])

In [9]:
ket('0').dag().full()

array([[1, 0]])

In [10]:
bra('0')*ket('0') 

<IPython.core.display.Math object>

ObjQuantico: dim =1 , shape = (1, 1)

$$ <1|0>=<0|1> = 0 $$

In [11]:
bra('1')*ket('0') 

<IPython.core.display.Math object>

ObjQuantico: dim =1 , shape = (1, 1)

## Produto externo

\begin{equation}
    \ket{0}\bra{0} =
\left(\begin{matrix}
        1 & 0 \\
        0 & 0
    \end{matrix}
\right)
\end{equation}

In [12]:
ket('0')*bra('0') 

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)

\begin{equation}
    \ket{1}\bra{1} =
\left(\begin{matrix}
        0 & 0 \\
        0 & 1
    \end{matrix}
\right)
\end{equation}

In [13]:
ket('1')*bra('1')

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)

\begin{equation}
    \ket{0}\bra{1} =
\left(\begin{matrix}
        0 & 1 \\
        0 & 0
    \end{matrix}
\right)
\end{equation}

In [14]:
ket('0')*bra('1') 

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)

## Operador(matriz) com estado(vetor)

O operador de destruição $ \hat{a} $ age nos estados de número \$ |n\rangle$ como:
$$
\hat{a} |n\rangle = \sqrt{n} |n-1\rangle
$$

No estado de vácuo:
$
\hat{a} |1\rangle = |0\rangle
$

Sua representação matricial na base de Fock é:
$$
\hat{a} =
\begin{bmatrix}
0 & \sqrt{1} & 0 & 0 & \cdots \\
0 & 0 & \sqrt{2} & 0 & \cdots \\
0 & 0 & 0 & \sqrt{3} & \cdots \\
\vdots & \vdots & \vdots & \ddots & \ddots
\end{bmatrix}
$$

In [15]:
N =5
# Cria os valores para a subdiagonal (sqrt de índices de 1 a dim-1)
subdiagonal = np.sqrt(np.arange(1, N))
# Monta a matriz com a subdiagonal
a_operator = np.diag(subdiagonal, k=1)
a_operator

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.41421356, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [16]:
def destruiçao(N):
    subdiag = np.sqrt(np.arange(1, N))# Monta os elementos na subdiagonal
    dt      = np.diag(subdiag, k=1) # Operador de destruição
    return ObjQuantico(dt)

\begin{equation}
    \hat{a}\ket{1} =
\left(\begin{matrix}
        1  \\
        0 
    \end{matrix}
\right) = \ket{0}
\end{equation}

In [17]:
destruiçao(2)*ket('1') 

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 1)

In [18]:
from qutip import  destroy,basis

destroy(2)*basis(2,0)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]]

Resposta do qutip

In [19]:
( destruiçao(2)*ket('0') ).full()

array([[0.],
       [0.]])

## Operador(matriz) com Operador(matriz)

In [20]:
from qutip import  create

destroy(2)*create(2)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [21]:
def criaçao(N):
    return  destruiçao(N).dag()

In [22]:
destruiçao(2)*criaçao(2)

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)

In [23]:
create(2)*destroy(2)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [24]:
criaçao(2)*destruiçao(2)

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)

## Produto tensorial 

In [25]:
criaçao(2)@criaçao(2)

<IPython.core.display.Math object>

ObjQuantico: dim =4 , shape = (4, 4)

In [26]:
bases(2,0)@bases(2,1)

<IPython.core.display.Math object>

ObjQuantico: dim =4 , shape = (4, 1)

In [27]:
Identidade(5)@criaçao(2)

<IPython.core.display.Math object>

ObjQuantico: dim =10 , shape = (10, 10)

# Divisão com escalar

In [28]:
bases(2,1)/np.sqrt(2)

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 1)

In [29]:
criaçao(2)/(1-1j)

TypeError: Divisão não suportada entre <class 'complex'> e ObjQuantico

Podemos evitar esse problema fazendo 

In [30]:
criaçao(2) *  (1/(1-1j))

<IPython.core.display.Math object>

ObjQuantico: dim =2 , shape = (2, 2)