<a href="https://colab.research.google.com/github/GubioGL/Simulador_quantico/blob/main/Aula_0_introdu%C3%A7%C3%A3oipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nese notbook irei reescrever as notas de aula do  
"Quantum mechanics lectures with QuTiP" link= https://qutip.org/qutip-tutorials/


Com objetivo de criar meu propriio qutip iremos não apenas executar os comando das aulas mais criar classes, objetos, funções iguais.

Nessa primeira versão iremos usar o numpy com base.

# Aula 0 : introdução ao qutip

QuTiP é um pacote python para cálculos e simulações numéricas de sistemas quânticos.

Inclui recursos para representar e fazer cálculos com objetos quânticos, como vetores de estado (funções de onda), como matrizes bras/kets/densidade, operadores quânticos de sistemas simples e compostos e superoperadores (úteis para definir equações mestras).

Também inclui 'solver' para uma evolução temporal de sistemas quânticos, de acordo com: equação de Schrodinger, equação de von Neuman, equações mestras, formalismo de Floquet, trajetórias quânticas de Monte-Carlo, implementações experimentais das equações mestras/de Schrodinger estocásticas.

Para poder compara com o pacote do qutip temos que primeiro intalar:

In [ ]:
!pip install qutip

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image
from qutip import (Qobj, about, basis, coherent, coherent_dm, create, destroy,
                   expect, fock, fock_dm, mesolve, qeye, sigmax, sigmay,
                   sigmaz, tensor, thermal_dm)

%matplotlib inline

A estrutura mais basica do qutip é a class qobj, que eles chamaram de objto quantico.


In [ ]:
q = Qobj([[1], [0]])
q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

$$|ket> =  \left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)$$

Como essa é um biblioteca ja tem validade a classe qobj é bem complicada de ser reproduzida com todas suas caracterista então tentaremos reproduzir apenas o basico com a biblioteca numpy e scipy.

In [ ]:
def ket(entrada_):

    if entrada_ == '0':
        entrada_  = np.array([[1], [0]])

    elif entrada_ == '1':
        entrada_  = np.array([[0], [1]])

    else:
        try:
            entrada_  = np.array(entrada_)
        except ValueError:
            print("Entrada invalida.")
    return entrada_

def bra(entrada_):
    return ket(entrada_).T

In [ ]:
state = ket('0')
state

array([[1],
       [0]])

In [ ]:
state2 = bra('0')
state2

array([[1, 0]])

In [ ]:
np.dot(state,state2)

array([[1, 0],
       [0, 0]])

In [ ]:
np.dot(state2,state)

array([[1]])

Obtemos nosso vetor desejado!

$$|ket> =  \left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)$$


$$< bra | =
\left(
    \begin{matrix}
        1.0 &  0.0
    \end{matrix}
\right)$$

note que o bra é o transporto do ket:

$$< bra | == (|ket>)^T  $$

e como esperado, o produto interno entre o bra e ket é 1.
$$< bra|ket> = 1  $$
por que:

$$
\left(\begin{matrix}
    1.0 &  0.0
\end{matrix}\right) *
\left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)
= 1*1 + 0*0 =1
$$

e no outro caso

\begin{equation}
    |ket>< bra | =
\left(\begin{matrix}
        1 & 0 \\
        0 & 0
    \end{matrix}
\right)
\end{equation}


In [ ]:
np.dot(state,state2).shape

(2, 2)

In [ ]:
def U(entrada_):

    if entrada_ == 'PauliX':
        entrada_ = np.matrix([[ 0, 1 ],[ 1, 0 ]])
    elif entrada_ == 'PauliY':
        entrada_ = np.matrix([[ 0, -1j ],[ 1j, 0 ]])
    elif entrada_ == 'PauliZ':
        entrada_ = np.matrix([[ 1, 0 ],[ 0, -1 ]])
    else:
        try:
            entrada_  = np.matrix(entrada_)
        except ValueError:
            print("Entrada invalida.")
    return entrada_

In [98]:
U('PauliY'),U('PauliX') , U('PauliZ') , U([ [-7,1+1j], [1-1j,-7] ])

(matrix([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
 matrix([[0, 1],
         [1, 0]]),
 matrix([[ 1,  0],
         [ 0, -1]]),
 matrix([[-7,  0],
         [ 0, -7]]))

In [109]:
# Exemplo de hamiltoniana
sz = U('PauliZ')
sy = U('PauliY')
H  = 1.0*sz + 0.1*sy

print("Qubit Hamiltonian = \n")
H

Qubit Hamiltonian = 



matrix([[ 1.+0.j ,  0.-0.1j],
        [ 0.+0.1j, -1.+0.j ]])

Se vc quiser obter o transpoto, deve fazer:

In [170]:
print("ket (numpy):\n",ket('0'))
print("ket^T (numpy):\n",ket('0').T,"\n")

q = Qobj([[1], [0]])
print("ket :",q)
print("ket^T :",q.trans())

ket (numpy):
 [[1]
 [0]]
ket^T (numpy):
 [[1 0]] 

ket : Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
ket^T : Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 0.]]


Parece igual

In [173]:
print("sy(numpy): \n",sy)
print("sy(numpy)^T: \n",sy.T,"\n")

Sy = Qobj([[0, -1j], [1j, 0]])  # the sigma-y Pauli operator
print("sy: \n",Sy)
print("sy^T: \n",Sy.trans())

sy(numpy): 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sy(numpy)^T: 
 [[ 0.+0.j  0.+1.j]
 [-0.-1.j  0.+0.j]] 

sy: 
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
sy^T: 
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]


Então para tiar o transporto apenas devemos usar .T

Muitas vezes vamos precisa tiar o conjugado + transposto de um vetor ou matrix, no qutip temo o .dag()

In [164]:
Sy = Qobj([[0, -1j], [1j, 0]])  # the sigma-y Pauli operator
print("sy: \n",Sy,'\n')
print("sy^T: \n",Sy.dag())

sy: 
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]] 

sy^T: 
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]


In [174]:
print("ket (numpy):\n",ket('0'))
print("ket^T (numpy):\n",np.conjugate(ket('0').T),"\n")


print("sy(numpy): \n",sy)
print("sy(numpy)^T: \n",np.conjugate(sy.T),"\n")

ket (numpy):
 [[1]
 [0]]
ket^T (numpy):
 [[1 0]] 

sy(numpy): 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sy(numpy)^T: 
 [[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]] 



Podemos criar um função para isso:

In [176]:
def dag(objeto):
    return np.conjugate(objeto.T)
print("ket (numpy):\n",ket('0'))
print("ket^T (numpy):\n",dag(ket('0')),"\n")
print("sy(numpy): \n",sy)
print("sy(numpy)^T: \n",dag(sy),"\n")

ket (numpy):
 [[1]
 [0]]
ket^T (numpy):
 [[1 0]] 

sy(numpy): 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sy(numpy)^T: 
 [[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]] 

