# Aula 5: 

In [1]:
import numpy as np
import sympy as sp
from IPython.display import display, Math
from scipy.linalg import expm

In [ ]:
class ObjQuantico:
    def __init__(self, data,latex_representation=None):
        self.dados = data
        self.latex_representation = latex_representation

    def definir_dados(self, data):
        self.dados = data

    def full(self):
        return self.dados
    
    def dim(self):
        return len(self.dados)
    
    def dag(self):
        return ObjQuantico(np.conjugate(self.dados.T))
    
    def traço(self):
        return np.trace(self.dados).real
    
    def Autovalores(self):
        return np.linalg.eigvals(self.dados)
    
    def Autovetores(self):
        return np.linalg.eig(self.dados)[1]
    
    def AutoValor_vetor(self):
        return np.linalg.eig(self.dados)[1]
    
    def expM(self):
        return ObjQuantico(expm(self.dados)) 

    def __repr__(self):
        if self.latex_representation:
            display(Math(self.latex_representation))
        else:
            display(Math(sp.latex(sp.Matrix(self.dados))))
        return f"ObjQuantico: dim ={self.dim()} , shape = {self.dados.shape}" 
    
    def __mul__(self, other):
        # Multiplicação para diferentes tipos
        if isinstance(other, ObjQuantico):  
            # Multiplicação matricial com outra instância de ObjQuantico
            return ObjQuantico(np.dot(self.dados, other.dados))
        elif np.isscalar(other):  # Multiplicação por escalar
            return ObjQuantico(self.dados * other)
        else:
            raise TypeError(f"Multiplicação não suportada entre {type(other)} e ObjQuantico")

    def __rmul__(self, other):
        if np.isscalar(other):  # Multiplicação reversa por escalar
            return ObjQuantico(self.dados * other)
        else:
            raise TypeError(f"Multiplicação não suportada entre {type(other)} e ObjQuantico")
        
    def __sub__(self, other):
        if isinstance(other, ObjQuantico):  
            # Subtração entre duas instâncias de ObjQuantico
            return ObjQuantico(self.dados - other.dados)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")
       
    def __add__(self, other):
        if isinstance(other, ObjQuantico):  
            # Soma os dados de dois objetos ObjQuantico
            return ObjQuantico(self.dados + other.dados)
        else:
            raise TypeError(f"Soma não suportada entre {type(other)} e ObjQuantico")
        
    def __sub__(self, other):
        if isinstance(other, ObjQuantico):  
            # Subtração entre duas instâncias de ObjQuantico
            return ObjQuantico(self.dados - other.dados)
        elif isinstance(other, np.ndarray):  # Subtração com arrays NumPy
            return ObjQuantico(self.dados - other)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")
    
    def __rsub__(self, other):
        if isinstance(other, np.ndarray):  # Subtração com arrays NumPy (comutada)
            return ObjQuantico(other - self.dados)
        else:
            raise TypeError(f"Subtração não suportada entre {type(other)} e ObjQuantico")   

    def __truediv__(self, other):
        if isinstance(other, (int, float)):  # Divisão por um número escalar
            return ObjQuantico(self.dados / other)
        else:
            raise TypeError(f"Divisão não suportada entre {type(other)} e ObjQuantico")
    
    def __rtruediv__(self, other):
        if isinstance(other, (int, float)):  # Divisão invertida por um número escalar
            return ObjQuantico(other / self.dados)
        else:
            raise TypeError(f"Divisão não suportada entre {type(other)} e ObjQuantico")     
    
    def __matmul__(self, other):
        """Implementa o operador @ para o produto tensorial."""
        if isinstance(other, ObjQuantico):
            return ObjQuantico(np.kron(self.full(), other.full()))
        else:
            raise TypeError(f"Operador @ não suportado entre {type(self)} e {type(other)}")

def bases(N,n):
    estadoinicial = np.zeros(shape=(N, 1))
    estadoinicial[n, 0] = 1
    return ObjQuantico(estadoinicial) 
  
def ket(entrada):
    if isinstance(entrada, str):
        if entrada == '0':
            dados = np.array([[1], [0]])
            latex_representation = r"$$ \ket{0} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
        elif entrada == '1':
            dados = np.array([[0], [1]])
            latex_representation = r"$$ \ket{1} $$"  # LaTeX para o ket |1>
            return ObjQuantico(dados, latex_representation)
    else:
        try:
            return ObjQuantico(entrada)
        except ValueError:
            return print("Entrada invalida.") 
         
def bra(entrada):
    if isinstance(entrada, str):
        if entrada == '0':
            dados = np.array([[1], [0]])
            latex_representation = r"$$ \bra{0} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
        elif entrada == '1':
            dados = np.array([[0], [1]])
            latex_representation = r"$$ \bra{1} $$"  # LaTeX para o ket |0>
            return ObjQuantico(dados, latex_representation)
    else:
        try:
            return ObjQuantico(entrada)
        except ValueError:
            return print("Entrada invalida.")      

def destruiçao(N):
    subdiag = np.sqrt(np.arange(1, N))# Monta os elementos na subdiagonal
    dt      = np.diag(subdiag, k=1) # Operador de destruição
    return ObjQuantico(dt)

def criaçao(N):
    return  destruiçao(N).dag()    
   
def Identidade(N):
    matriz = np.identity(N)
    return ObjQuantico(matriz) 

def pauliX():
    m = np.array([[ 0, 1 ],[ 1, 0 ]])
    latex_representation = r"$$ \hat{\sigma_x} $$"
    return ObjQuantico(m,latex_representation)

def pauliY():
    m = np.array([[ 0, -1j ],[ 1j, 0 ]])
    latex_representation = r"$$ \hat{\sigma_y} $$"  
    return ObjQuantico(m,latex_representation)

def pauliZ():
    m = np.array([[ 1, 0 ],[ 0, -1 ]])
    latex_representation = r"$$ \hat{\sigma_z} $$"  
    return ObjQuantico(m,latex_representation)


###  Base de fock

In [3]:
def Fock(N, n=0):
    "Equivalente a função bases"
    return bases(N, n)

Fock(N=5)

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 1)

### Coerente

Para escrever o estado coerente tem duas forma :


(1) OPERADOR: forma compacta usando o operador de deslocamento.
$$
|\alpha\rangle =D(\alpha)|0\rangle =  e^{\alpha a^\dagger - \alpha^* a} |0\rangle
$$

(2)ANALITICO: expansão na base de fock
$$
|\alpha\rangle = e^{-\frac{|\alpha|^2}{2}} \sum_{n=0}^{\infty} \frac{\alpha^n}{\sqrt{n!}} |n\rangle

$$

### 1º forma

In [4]:
# 1 forma
N       = 5
estado  = bases(N,0)
estado

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 1)

In [5]:
def criaçao(N):
    return  destruiçao(N).dag()

Agora vamos criar o operador de deslocamento

In [6]:
from scipy.linalg import expm
alpha =0.5
alpha * destruiçao(N).dag() - np.conj(alpha) * destruiçao(N)

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 5)

In [7]:
data = alpha * destruiçao(N).dag() - np.conj(alpha) * destruiçao(N)
data.full()

array([[ 0.        , -0.5       ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  0.        , -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.        , -0.8660254 ,  0.        ],
       [ 0.        ,  0.        ,  0.8660254 ,  0.        , -1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ]])

In [8]:
from scipy.linalg import expm
def expM(matriz):
    return ObjQuantico(expm(matriz.full()))  


In [9]:
alpha =0.5
D = expM(alpha * destruiçao(N).dag() - np.conj(alpha) * destruiçao(N))
D

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 5)

Conferindo com o qutip

In [10]:
from qutip import destroy
(alpha * destroy(N).dag() - np.conj(alpha) * destroy(N)).expm()


Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.88249693 -0.44124785  0.15601245 -0.04496584  0.01173405]
 [ 0.44124785  0.66186201 -0.54613558  0.24675339 -0.08993168]
 [ 0.15601245  0.54613558  0.46996952 -0.5734898   0.35725922]
 [ 0.04496584  0.24675339  0.5734898   0.25891541 -0.73563789]
 [ 0.01173405  0.08993168  0.35725922  0.73563789  0.56831097]]

In [11]:
D*estado

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 1)

In [12]:
def coerente(alpha,N):
    estado  = bases(N,0) # estado inicinal no vacuo
    D       = alpha * destruiçao(N).dag() - np.conj(alpha) * destruiçao(N)
    D       = D.expM()
    return D*estado

In [13]:
coerente(0.5,5)

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 1)

### 2º forma

In [14]:
from  scipy.special import factorial

# 2 forma
estado  = np.zeros(shape=(N,1),dtype=complex)
n       = np.arange(N)
estado[:,0] = np.exp(-abs(alpha) ** 2 / 2.0) * (alpha ** (n))/np.sqrt(factorial(n))
estado

array([[0.8824969 +0.j],
       [0.44124845+0.j],
       [0.15600489+0.j],
       [0.04503473+0.j],
       [0.01125868+0.j]])

In [15]:
def coerente(N,alpha,metodo ="operador"):
    if metodo == "operador" :
        estado  = bases(N,0) # estado inicinal no vacuo
        D       = alpha * destruiçao(N).dag() - np.conj(alpha) * destruiçao(N)
        D       = D.expM()
        return D*estado
    
    elif metodo == "analitico":    
        estado  = np.zeros(shape=(N,1),dtype=complex)
        n       = np.arange(N)
        estado[:,0] = np.exp(-(abs(alpha) ** 2 )/ 2.0) * (alpha**n)/np.sqrt(factorial(n))
        return estado
    else:
        raise TypeError(
            "A opção de método tem as seguintes opções :'operador' ou 'analitico'")

In [16]:
alpha   = 0.5+5j
N       = 5 
coerente(N,alpha,metodo ="operador")

<IPython.core.display.Math object>

ObjQuantico: dim =5 , shape = (5, 1)

In [17]:
coerente(N=5,alpha=0.5+5j,metodo ="analitico")

array([[ 3.28875988e-06+0.00000000e+00j],
       [ 1.64437994e-06+1.64437994e-05j],
       [-5.75562342e-05+1.16275221e-05j],
       [-5.01808186e-05-1.62793960e-04j],
       [ 3.94439696e-04-1.66150537e-04j]])