<a href="https://colab.research.google.com/github/GubioGL/Simulador_quantico/blob/main/Aula_0_introdu%C3%A7%C3%A3oipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nese notbook irei reescrever as notas de aula do  
"Quantum mechanics lectures with QuTiP" link= https://qutip.org/qutip-tutorials/


Com objetivo de criar meu propriio qutip iremos não apenas executar os comando das aulas mais criar classes, objetos, funções iguais.

Nessa primeira versão iremos usar o numpy com base.

# Aula 0 : Introdução e conceitos basicos

QuTiP é um pacote python para cálculos e simulações numéricas de sistemas quânticos.

Inclui recursos para representar e fazer cálculos com objetos quânticos, como vetores de estado (funções de onda), como matrizes bras/kets/densidade, operadores quânticos de sistemas simples e compostos e superoperadores (úteis para definir equações mestras).

Também inclui 'solver' para uma evolução temporal de sistemas quânticos, de acordo com: equação de Schrodinger, equação de von Neuman, equações mestras, formalismo de Floquet, trajetórias quânticas de Monte-Carlo, implementações experimentais das equações mestras/de Schrodinger estocásticas.

Para poder compara com o pacote do qutip temos que primeiro intalar:

In [1]:
import matplotlib.pyplot as plt
import numpy as np

from IPython.display import Image
from qutip import (Qobj, about, basis, coherent, coherent_dm, create, destroy,
                   expect, fock, fock_dm, mesolve, qeye, sigmax, sigmay,
                   sigmaz, tensor, thermal_dm)

%matplotlib inline

A estrutura mais basica do qutip é a class qobj, que eles chamaram de objto quantico.


In [2]:
q = Qobj([[1], [0]])
q

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

$$\ket{0} =  \left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)$$

Como essa é um biblioteca ja tem validade a classe qobj é bem complicada de ser reproduzida com todas suas caracterista então tentaremos reproduzir apenas o basico com a biblioteca numpy e scipy.

In [3]:
def ket(entrada_):
    if entrada_ == '0':
        entrada_  = np.array([[1], [0]])
    elif entrada_ == '1':
        entrada_  = np.array([[0], [1]])
    else:
        try:
            entrada_  = np.array(entrada_)
        except ValueError:
            print("Entrada invalida.")
    return entrada_


In [4]:
ket_0 = ket('0')
ket_0

array([[1],
       [0]])

Se você quiser obter o transpoto, deve fazer:

In [5]:
print(" ket (numpy):\n",ket('0'))
print("ket . T (numpy):\n",ket('0').T,"\n")

 ket (numpy):
 [[1]
 [0]]
ket . T (numpy):
 [[1 0]] 



Podemos verificar com o qutip

In [6]:
q = Qobj([[1], [0]])
print("ket :",q)
print("ket^T :",q.trans())

ket : Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]
ket^T : Quantum object: dims=[[1], [2]], shape=(1, 2), type='bra', dtype=Dense
Qobj data =
[[1. 0.]]


In [7]:
def bra(entrada_):
    return ket(entrada_).T

bra_0 = bra('0')
bra_0

array([[1, 0]])

Obtemos nosso vetor desejado!

$$ \ket{0} =  \left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)$$


$$ \bra{0} =
\left(
    \begin{matrix}
        1.0 &  0.0
    \end{matrix}
\right)$$

note que o bra é o transporto do ket:

$$ < bra | = (|ket>)^T  $$

e como esperado, o produto interno entre o bra e ket é 1.

COMENTAR SOBRE A NORMALIZAÇÃO


$$< bra|ket> = 1  $$
$$< 0|0> = 1  $$
por que:

$$
\left(\begin{matrix}
    1.0 &  0.0
\end{matrix}\right) *
\left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)
= 1*1 + 0*0 =1
$$

In [8]:
np.dot(ket_0,bra_0)

array([[1, 0],
       [0, 0]])

In [9]:
ket_1 = ket('1')
bra_1 = bra('1')
np.dot(bra_1,ket_1)[0][0]

1

In [10]:
print( np.dot(bra_0,ket_1)[0][0])
print( np.dot(bra_1,ket_0)[0][0])

0
0


Nessa caso o produto interno da zero , pq os vetores são ortogonal. 

Podemos fazer o produto externo , invertendo a ordem do vetor

In [11]:
np.dot(ket_0,bra_0)

array([[1, 0],
       [0, 0]])


\begin{equation}
    |ket>< bra | 
\end{equation}

\begin{equation}
    \ket{0}\bra{0} =
\left(\begin{matrix}
        1 & 0 \\
        0 & 0
    \end{matrix}
\right)
\end{equation}


Criando as matrizes de pauli

In [12]:
def U(entrada_):

    if entrada_ == 'PauliX':
        entrada_ = np.matrix([[ 0, 1 ],[ 1, 0 ]])
    elif entrada_ == 'PauliY':
        entrada_ = np.matrix([[ 0, -1j ],[ 1j, 0 ]])
    elif entrada_ == 'PauliZ':
        entrada_ = np.matrix([[ 1, 0 ],[ 0, -1 ]])
    else:
        try:
            entrada_  = np.matrix(entrada_)
        except ValueError:
            print("Entrada invalida.")
    return entrada_

In [13]:
U('PauliY'),U('PauliX') , U('PauliZ') , U([ [-7,1+1j], [1-1j,-7] ])

(matrix([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
 matrix([[0, 1],
         [1, 0]]),
 matrix([[ 1,  0],
         [ 0, -1]]),
 matrix([[-7.+0.j,  1.+1.j],
         [ 1.-1.j, -7.+0.j]]))

In [14]:
U('PauliY').T

matrix([[ 0.+0.j,  0.+1.j],
        [-0.-1.j,  0.+0.j]])

In [15]:
# Exemplo de hamiltoniana
sz = U('PauliZ')
sy = U('PauliY')
H  = 1.0*sz + 0.2*sy

print("Qubit Hamiltonian = \n",H)

Qubit Hamiltonian = 
 [[ 1.+0.j   0.-0.2j]
 [ 0.+0.2j -1.+0.j ]]


Muitas vezes vamos precisa tirar o conjugado + transposto de um vetor ou matrix, no qutip temo o .dag()

In [16]:
Sy = Qobj([[0, -1j], [1j, 0]])  # the sigma-y Pauli operator
Sy

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

In [17]:
Sy.dag()

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]

Podemos fazer isso , usado 

*        np.conjugate()
*       .T

Primero para o vetores:

In [18]:
vetor = [[1 + 1j], [-7 + 7j]]
print("ket (numpy):\n",ket(vetor))
print("ket^T (numpy):\n",np.conjugate(ket(vetor).T),"\n")

ket (numpy):
 [[ 1.+1.j]
 [-7.+7.j]]
ket^T (numpy):
 [[ 1.-1.j -7.-7.j]] 



Podemos fazer o mesmo para matrizes

In [19]:
print("sy(numpy): \n",sy)
print("sy(numpy)^T: \n",np.conjugate(sy.T),"\n")

sy(numpy): 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sy(numpy)^T: 
 [[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]] 



Podemos criar um função para isso:

In [20]:
def dag(objeto):
    return np.conjugate(objeto.T)
print("ket:\n",ket('0'))
print("ket.dag() :\n",dag(ket('0')),"\n")
print("sy: \n",sy)
print("sy.dag(): \n",dag(sy),"\n")

ket:
 [[1]
 [0]]
ket.dag() :
 [[1 0]] 

sy: 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sy.dag(): 
 [[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]] 



Nossa hamiltoniana é 

In [21]:
H

matrix([[ 1.+0.j ,  0.-0.2j],
        [ 0.+0.2j, -1.+0.j ]])

queremos calcular o traço da matriz

In [22]:
# The trace
np.trace(H).real

0.0

Definindo nosso função do traço

In [23]:
def tr(matriz):
    return np.trace(matriz).real

In [24]:
# Eigen energies
np.linalg.eigvals(H)

array([ 1.0198039+0.j, -1.0198039+0.j])

In [25]:
np.linalg.eig(H)[1]

matrix([[0.99513333+0.j        , 0.        +0.09853762j],
        [0.        +0.09853762j, 0.99513333+0.j        ]])

Definindo nosso função do do valor esperado e autofunçoes

In [26]:
def Autoenergias(matriz):
    return np.trace(matriz).real
def Autovalores(matriz):
    return np.linalg.eig(matriz)[1]

Facilitando para o usuario

In [27]:
# Vetor de estado (Estado de fock dos modos de oscilação)

N = 2  # Numero de estado no espaço do Hilbert 
n = 0  # O estado que será ocupado

basis(N, n) # n=0 |0> e n=1   |1>


Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

Essa função é mais geral que parece , ele serve para criar um estado de dimenção N. Diferente do que tinhamos criando antes que tinha dimensao N=2 sempre

In [28]:
N = 2  # Numero de estado no espaço do Hilbert 
n = 0  # O estado que será ocupado

basis(N, n) # n=0 |0> e n=1   |1>

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

In [29]:
basis(5, 3) # n=0 |0> e n=1   |1>

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [30]:
basis(5, 3).full

<bound method Qobj.full of Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]>

In [31]:
np.zeros(shape=(5,1),dtype=complex)

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [32]:
estadoinicial   = np.zeros(shape=(5,1),dtype=complex)
indice          = 3 
estadoinicial[indice,0] = 1
estadoinicial.real

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [33]:
def bases(N,n):
    estadoinicial   = np.zeros(shape=(N,1))
    estadoinicial[n,0] = 1
    return estadoinicial

In [34]:
bases(N=4,n=1)

array([[0.],
       [1.],
       [0.],
       [0.]])

Vamos criar um estado coerente

In [35]:
# a coherent state
coherent(N=5, alpha=0.5)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.88249693]
 [0.44124785]
 [0.15601245]
 [0.04496584]
 [0.01173405]]

Para escrever o estado coerente tem duas forma :


(1) OPERADOR: forma compacta usando o operador de deslocamento.
$$
|\alpha\rangle =D(\alpha)|0\rangle =  e^{\alpha a^\dagger - \alpha^* a} |0\rangle
$$

(2)ANALITICO: expansão na base de fock
$$
|\alpha\rangle = e^{-\frac{|\alpha|^2}{2}} \sum_{n=0}^{\infty} \frac{\alpha^n}{\sqrt{n!}} |n\rangle

$$

In [36]:
# 1 forma
N =5
estado  = bases(N,0)
estado

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]])

Para o proximo passo precisamos criar o operado de destruiçao.
O operador de destruição $ \hat{a} $ age nos estados de número \$ |n\rangle$ como:
$$
\hat{a} |n\rangle = \sqrt{n} |n-1\rangle
$$

No estado de vácuo:
$
\hat{a} |0\rangle = 0
$

Sua representação matricial na base de Fock é:
$$
\hat{a} =
\begin{bmatrix}|0\rangle
0 & \sqrt{1} & 0 & 0 & \cdots \\
0 & 0 & \sqrt{2} & 0 & \cdots \\
0 & 0 & 0 & \sqrt{3} & \cdots \\
\vdots & \vdots & \vdots & \ddots & \ddots
\end{bmatrix}
$$

In [37]:
# Cria os valores para a subdiagonal (sqrt de índices de 1 a dim-1)
subdiagonal = np.sqrt(np.arange(1, N))
# Monta a matriz com a subdiagonal
a_operator = np.diag(subdiagonal, k=1)
a_operator

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.41421356, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

### Operador deslocamento e destruição

Agora vamos criar o operador de deslocamento

In [38]:
from scipy.linalg import expm
alpha =0.5
D = expm(alpha * dag(a_operator) - np.conj(alpha) * a_operator)
D

array([[ 0.88249693, -0.44124785,  0.15601245, -0.04496584,  0.01173405],
       [ 0.44124785,  0.66186201, -0.54613558,  0.24675339, -0.08993168],
       [ 0.15601245,  0.54613558,  0.46996952, -0.5734898 ,  0.35725922],
       [ 0.04496584,  0.24675339,  0.5734898 ,  0.25891541, -0.73563789],
       [ 0.01173405,  0.08993168,  0.35725922,  0.73563789,  0.56831097]])

In [39]:
np.dot(D,estado)

array([[0.88249693],
       [0.44124785],
       [0.15601245],
       [0.04496584],
       [0.01173405]])

In [40]:
def coerente(alpha,N):
    estado  = bases(N,0).real # estado inicinal no vacuo
    subdiag = np.sqrt(np.arange(1, N))# Monta os elementos na subdiagonal
    a       = np.diag(subdiag, k=1) # Operador de destruição
    D       = expm(alpha * dag(a) - np.conj(alpha) * a)
    return np.dot(D,estado)

In [41]:
from  scipy.special import factorial

# 2 forma
estado  = np.zeros(shape=(N,1),dtype=complex)
n       = np.arange(N)
estado[:,0] = np.exp(-abs(alpha) ** 2 / 2.0) * (alpha ** (n))/np.sqrt(factorial(n))
estado

array([[0.8824969 +0.j],
       [0.44124845+0.j],
       [0.15600489+0.j],
       [0.04503473+0.j],
       [0.01125868+0.j]])

In [42]:
def coerente(N,alpha,metodo ="operador"):
    
    if metodo == "operador" :
        
        estado  = bases(N,0) # estado inicinal no vacuo
        subdiag = np.sqrt(np.arange(1, N))# Monta os elementos na subdiagonal
        a       = np.diag(subdiag, k=1) # Operador de destruição
        D       = expm(alpha * dag(a) - np.conj(alpha) * a)
        
        return np.dot(D,estado)
    
    elif metodo == "analitico":
        
        estado  = np.zeros(shape=(N,1),dtype=complex)
        n       = np.arange(N)
        estado[:,0] = np.exp(-(abs(alpha) ** 2 )/ 2.0) * (alpha**n)/np.sqrt(factorial(n))
        
        return estado
    else:
        raise TypeError(
            "A opção de método tem as seguintes opções :'operador' ou 'analitico'")

In [43]:
alpha   = 0.5+5j
N       = 5 

In [44]:
coerente(N,alpha,metodo ="operador")

array([[ 0.91194074+5.55111512e-17j],
       [ 0.03647048+3.64704774e-01j],
       [-0.17126047+3.45980742e-02j],
       [-0.0034744 -1.12714606e-02j],
       [-0.05340481+2.24958041e-02j]])

In [45]:
coherent(N, alpha,method='operator')

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.91194074-1.11022302e-16j]
 [ 0.03647048+3.64704774e-01j]
 [-0.17126047+3.45980742e-02j]
 [-0.0034744 -1.12714606e-02j]
 [-0.05340481+2.24958041e-02j]]

In [46]:
coerente(N=5,alpha=0.5+5j,metodo ="analitico")

array([[ 3.28875988e-06+0.00000000e+00j],
       [ 1.64437994e-06+1.64437994e-05j],
       [-5.75562342e-05+1.16275221e-05j],
       [-5.01808186e-05-1.62793960e-04j],
       [ 3.94439696e-04-1.66150537e-04j]])

In [47]:
coherent(N, alpha,method='analytic')

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[ 3.28875988e-06+0.00000000e+00j]
 [ 1.64437994e-06+1.64437994e-05j]
 [-5.75562342e-05+1.16275221e-05j]
 [-5.01808186e-05-1.62793960e-04j]
 [ 3.94439696e-04-1.66150537e-04j]]

### Estado de Fock 

In [48]:
def Fock(N, n=0):
    "Equivalente a função bases"
    return bases(N, n)

In [49]:
Fock(N=5)

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [50]:
fock(5,n=0)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

### Matriz densidade

A matriz densidade  para um estado puro $ |\psi\rangle $:
$$
\rho = |\psi\rangle \langle \psi|
$$


Para um estado misto:

$$
\rho = \sum_i p_i |\psi_i\rangle \langle \psi_i|
$$

Aqui, $ \sum_i p_i = 1 $, e $ 0 \leq p_i \leq 1 $.


In [51]:
# Estados puros 
N = 4
alpha =1
psi = coerente(N,alpha)
psi

array([[0.60605894],
       [0.6100857 ],
       [0.41242505],
       [0.30065525]])

In [52]:
rho = np.dot(psi,dag(psi))
rho

array([[0.36730744, 0.36974789, 0.24995389, 0.1822148 ],
       [0.36974789, 0.37220456, 0.25161463, 0.18342547],
       [0.24995389, 0.25161463, 0.17009442, 0.12399776],
       [0.1822148 , 0.18342547, 0.12399776, 0.09039358]])

In [53]:
coherent_dm(4,alpha)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.36730744 0.36974789 0.24995389 0.1822148 ]
 [0.36974789 0.37220456 0.25161463 0.18342547]
 [0.24995389 0.25161463 0.17009442 0.12399776]
 [0.1822148  0.18342547 0.12399776 0.09039358]]

In [54]:
# para o estado de fock é equivalente
psi = Fock(N=4,n=2)
rho = np.dot(psi,dag(psi))
rho

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [55]:
def matrizdensidade(probabilities, states, puro=True):
    
    if puro == True:
        return np.dot(state,dag(state))
    
    else:   
        # Verificar se as probabilidades somam 1
        if not np.isclose(sum(probabilities), 1):
            raise ValueError("As probabilidades devem somar 1.")
        
        # Verificar se cada estado está normalizado
        for state in states:
            if not np.isclose(np.linalg.norm(state), 1):
                raise ValueError("Todos os estados devem ser normalizados.")
             
        # Criar a matriz densidade
        rho = np.zeros((states[0].shape[0], states[0].shape[0]), dtype=complex)
        
        for p, state in zip(probabilities, states):
            rho += p * np.outer(state, state.conj())  # |ψ⟩⟨ψ|
    
    return rho


Exemplo de estado misto

In [56]:
probabilities = [0.5, 0.5]
matrizdensidade(probabilities, [bases(N=2,n=0),bases(N=2,n=1)], puro=False)

array([[0.5+0.j, 0. +0.j],
       [0. +0.j, 0.5+0.j]])

## Operadores

In [57]:
# ja fizemso os operadores de pauli
# Operador de deslocamento e criamos o operador de destruição
# função do operador destruição

def destruiçao(N):
    subdiag = np.sqrt(np.arange(1, N))# Monta os elementos na subdiagonal
    return np.diag(subdiag, k=1) # Operador de destruição
destruiçao(2)

array([[0., 1.],
       [0., 0.]])

In [58]:
def criaçao(N):
    return  dag(destruiçao(N))
criaçao(2)

array([[0., 0.],
       [1., 0.]])

O operador de posição é dado por:

$$
\hat{x} = \frac{\hat{a} + \hat{a}^\dagger}{\sqrt{2}}
$$

In [59]:
# operador posição
def operador_x(N):
    return (destruiçao(N) + dag(destruiçao(N)))/np.sqrt(2)
operador_x(4)

array([[0.        , 0.70710678, 0.        , 0.        ],
       [0.70710678, 0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        , 1.22474487],
       [0.        , 0.        , 1.22474487, 0.        ]])

O operador de momento é dado por:

$$
\hat{p} = \frac{\hat{a} - \hat{a}^\dagger}{i \sqrt{2}}
$$

In [60]:
# operador momento
def operador_p(N):
    return -1j*(destruiçao(N) - dag(destruiçao(N)))/np.sqrt(2)
operador_p(4)

array([[0.-0.j        , 0.-0.70710678j, 0.-0.j        , 0.-0.j        ],
       [0.+0.70710678j, 0.-0.j        , 0.-1.j        , 0.-0.j        ],
       [0.-0.j        , 0.+1.j        , 0.-0.j        , 0.-1.22474487j],
       [0.-0.j        , 0.-0.j        , 0.+1.22474487j, 0.-0.j        ]])

O comutador entre $ \hat{x} $ e $ \hat{p} $ é dado por:
$$
[\hat{A}, \hat{B}] = AB-BA
$$
$$
[\hat{x}, \hat{p}] = i
$$







In [61]:
# comutador
def comutador(op1, op2):
    return np.dot(op1,op2) - np.dot(op2,op1)

comutador(destruiçao(5),criaçao(5))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0., -4.]])

In [62]:
comutador(operador_x(5),operador_p(5))

array([[0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-4.j]])

In [63]:
a = destroy(5)
def commutator(op1, op2):
    return op1 * op2 - op2 * op1
commutator(a, a.dag())

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]

Obs:  O resultado deveria ser a identidade(i*I,I) nos dos casos!, mas aparece um 4 no ultimo termo.

Por quê? Porque truncamos o espaço de Hilbert. Mas tudo bem, desde que o maior estado de Fock não esteja envolvido na dinâmica no nosso espaço de Hilbert truncado. Se estiver, a aproximação que a truncagem introduz pode ser um problema.

In [64]:
commutator(a, a.dag())

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]

In [65]:
qeye(4)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dia, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [66]:
def Identidade(N):
    return np.identity(N)
Identidade(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Produto tensorial

In [67]:
np.kron(U('PauliZ'),Identidade(2))

matrix([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0., -1., -0.],
        [ 0.,  0., -0., -1.]])

In [68]:
def produto_tensorial(op1,op2):
    return np.kron(op1,op2)

Agora estamos pronto para criar uma hamiltoniana de dois qutis acoplado

$$
\hat{H} = \frac{\hbar \omega}{2} \left( \hat{\sigma}_z^{(1)} + \hat{\sigma}_z^{(2)} \right) + J \hat{\sigma}_x^{(1)} \hat{\sigma}_x^{(2)}
$$


In [69]:
epsilon = [1.0, 1.0]
g = 0.1

sz1 = produto_tensorial(U('PauliZ'), Identidade(2))
sz2 = produto_tensorial(Identidade(2), U('PauliZ'))

H = epsilon[0] * sz1 + epsilon[1] * sz2 + g * produto_tensorial(U('PauliX'), U('PauliX'))

H

matrix([[ 2. ,  0. ,  0. ,  0.1],
        [ 0. ,  0. ,  0.1,  0. ],
        [ 0. ,  0.1,  0. ,  0. ],
        [ 0.1,  0. ,  0. , -2. ]])

$$
\hat{H} = \frac{\hbar \omega_0}{2} \hat{\sigma}_z + \hbar \omega a^\dagger a + \hbar g \left( \hat{\sigma}_+ a + \hat{\sigma}_- a^\dagger \right)
$$


In [ ]:
wc  = 1.0  # Frequência da cavidade
wa  = 1.0  # Frequência do atomo
g   = 0.1  # Acoplamento
basefock = 2

# cavity mode operator
a = produto_tensorial(destruiçao(basefock), Identidade(2))

# qubit/atom operators
sz = produto_tensorial(Identidade(basefock), U('PauliZ'))  # sigma-z operator
sm = produto_tensorial(Identidade(basefock), destruiçao(2))  # sigma-minus operator

# the Jaynes-Cumming Hamiltonian
H_acomplamento = g * (np.dot(a,dag(sm)) + np.dot(dag(a),sm))
H = wc * dag(a) * a - 0.5 * wa * sz + H_acomplamento
H

matrix([[-0.5,  0. ,  0. ,  0. ],
        [ 0. ,  0.5,  0.1,  0. ],
        [ 0. ,  0.1, -0.5,  0. ],
        [ 0. ,  0. ,  0. ,  0.5]])