Nessa segunda aula iremos juntar as funções em um classe.

# Aula 1 : Criando a classe base

In [1]:

import numpy as np
import sympy as sp

from scipy.linalg import expm

from  scipy.special import factorial
from qutip import (Qobj, about, basis, coherent, coherent_dm, create, destroy,
                   expect, fock, fock_dm, mesolve, qeye, sigmax, sigmay,
                   sigmaz, tensor, thermal_dm)

In [ ]:
class ObjQuantico:
    def __init__(self, data):
        self.dados = data

    def definir_dados(self, data):
        self.dados = data

    def full(self):
        return self.dados
    
    def dim(self):
        return len(self.dados)
    
    def dag(self):
        return ObjQuantico(np.conjugate(self.dados.T))
    
    def traço(self):
        return np.trace(self.dados).real
    
    def Autovalores(self):
        return np.linalg.eigvals(self.dados)
    
    def Autovetores(self):
        return np.linalg.eig(self.dados)[1]
    
    def AutoValor_vetor(self):
        return np.linalg.eig(self.dados)[1]
             
         
def bases(N,n):
    estadoinicial = np.zeros(shape=(N, 1))
    estadoinicial[n, 0] = 1
    return ObjQuantico(estadoinicial) 


$$\ket{0} =  \left(\begin{matrix}1.0\\0.0\\\end{matrix}\right)$$

In [ ]:
bases(2,0).full()

array([[1.],
       [0.]])

$$\ket{1} =  \left(\begin{matrix}0.0\\1.0\\\end{matrix}\right)$$

In [4]:
bases(2,1).full()

array([[0.],
       [1.]])

Vetor aleatorio

In [5]:
matriz = np.array([[0+7j],[1-7j]])
quantum = ObjQuantico(matriz)
quantum.full()

array([[0.+7.j],
       [1.-7.j]])

In [6]:
def ket(entrada):
    if entrada == '0':
        return bases(2,0)
    elif entrada == '1':
        return  bases(2,1)
    else:
        try:
            return ObjQuantico(entrada).full()
        except ValueError:
            return print("Entrada invalida.")

In [7]:
ket('1').dag().full()

array([[0., 1.]])

In [8]:
ket('1').dag().full()

array([[0., 1.]])

In [9]:
def bra(entrada):
    return ket(entrada).dag()

In [10]:
bra("0").full()

array([[1., 0.]])

In [11]:
bra("0").dag().full()

array([[1.],
       [0.]])

In [12]:
np.dot(ket('1'),bra("0"))

TypeError: unsupported operand type(s) for *: 'ObjQuantico' and 'ObjQuantico'

Nosso proximo passo é adicionar *, / + e - na classe